sudo: false
language: objective-c
os: osx
xcode_project: GroupedArraySample/GroupedArraySample.xcodeproj
xcode_sdk: iphonesimulator11.0
osx_image: xcode9
matrix:
  include:
    - xcode_sdk: iphonesimulator
      xcode_scheme: GroupedArraySample-iOS
    - xcode_sdk: macosx
      xcode_scheme: GroupedArraySample-Mac

before_install:
  - gem install slather --no-ri --no-rdoc
  
after_success: slather
